FROM golang:1.15.8-alpine

RUN set -ex; \
    apk update; \
    apk add --no-cache git

WORKDIR /go/src/go-blog
COPY . .

# Execute tests
CMD CGO_ENABLED=0 go test -v ./... -coverprofile coverage.out && go tool cover -html=coverage.out -o coverage.html && go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}'
