version: "3.7"
services: 
  database:
    image: postgres
    restart: always
    env_file: .env
    ports: 
      - 5432:5432
    volumes: 
      - database_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: go-blog-server:1.0
    volumes:
      - .:/go/src/blog
    env_file: .env
    depends_on: 
      - database
    ports: 
      - 8080:8080
volumes: 
  database_data:
    driver: local
    