version: "3.7"
services: 
  database:
    image: postgres
    restart: always
    env_file: .env
    ports: 
      - 5432:5432
  server:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    env_file: .env
    depends_on: 
      - database
    ports: 
      - 8080:8080
    